# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2e64f5b8a85a06b75712ae10d5aa4de3eac5a5b8c6fef9b810500986bd9ad780c1dc9c1a4ea7f0673ebb068515a3775ea1c2cc4963312bb2b3b2044ef84de2da

test:
  secret_key_base: 0c3ed5badf3f2d31e9c51c5dd4865ba4309c7bab94acd52eb0312701095e379cf341dc2fb3e3879218d3f36e5a5dab2cc7ee5d79461d1c2d4332747d095b4d2a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
